import CoreLocation
import SwiftUI
#if canImport(UIKit)
    import UIKit
#endif

/// Full project detail screen. Shows overview, images, AI preview,
/// materials, estimates, and activity in a scrollable layout.
/// Loaded by project ID from the navigation stack.
struct ProjectDetailView: View {
    let projectId: String
    /// When the view opens with this set to `true`, an AI preview generation
    /// is automatically kicked off using the project's description as soon as
    /// the project loads — provided there are no existing generations and no
    /// run is already in flight. Used by the creation flow's toggle.
    var autoGenerateOnOpen: Bool = false

    @State private var viewModel = ProjectDetailViewModel()
    @State private var hasAutoGenerated = false
    @State private var showEditSheet = false
    @State private var isCreatingEstimate = false
    @State private var isGeneratingAIEstimate = false
    @State private var showDeleteConfirmation = false
    @State private var isDeleting = false

    /// Estimate export state. `exportingEstimateId` shows the inline
    /// progress on the estimate row; `exportProgressMessage` drives the
    /// full-screen overlay; `exportedPDF` triggers the share sheet once
    /// the PDF is ready (whether freshly rendered or re-downloaded from a
    /// saved export).
    @State private var exportingEstimateId: String?
    @State private var exportProgressMessage: String?
    @State private var exportedPDF: ExportedPDF?

    @AppStorage("estimatePDFIncludeBeforeAfter")
    private var includeBeforeAfterImages: Bool = true

    private struct ExportedPDF: Identifiable, Hashable {
        let url: URL
        var id: URL { url }
    }

    /// Map measurement sheets. Presenting these as full-screen covers
    /// avoids a NavigationSplitView quirk where the first
    /// `router.projectsPath.append(...)` from a deep view is swallowed
    /// until something else triggers a layout pass (which is why the
    /// button "did nothing" until the user switched tabs).
    @State private var showLawnMeasurement = false
    @State private var showRoofScouting = false

    @Environment(AppRouter.self) private var router
    @Environment(FeatureGateCoordinator.self) private var featureGateCoordinator
    @Environment(PaywallPresenter.self) private var paywallPresenter
    @Environment(AppState.self) private var appState

    var body: some View {
        Group {
            if viewModel.isLoading && viewModel.project == nil {
                LoadingStateView(message: "Loading project...")
            } else if let error = viewModel.errorMessage, viewModel.project == nil {
                RetryStateView(message: error) {
                    Task { await viewModel.loadProject(id: projectId) }
                }
            } else if let project = viewModel.project {
                projectContent(project)
            } else {
                // Fallback: if task didn't fire, show loading and trigger load
                LoadingStateView(message: "Loading project...")
                    .onAppear {
                        Task { await viewModel.loadProject(id: projectId) }
                    }
            }
        }
        .navigationTitle(viewModel.project?.title ?? "Project")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItemGroup(placement: .primaryAction) {
                ShareLink(
                    item: "Check out this project: \(viewModel.project?.title ?? "")",
                    subject: Text(viewModel.project?.title ?? "Project"),
                    message: Text("ProEstimate AI project details")
                ) {
                    Image(systemName: "square.and.arrow.up")
                }
                .accessibilityLabel("Share")
                .accessibilityHint("Share this project")

                Menu {
                    Button {
                        showEditSheet = true
                    } label: {
                        Label("Edit Project", systemImage: "pencil")
                    }

                    Divider()

                    Button(role: .destructive) {
                        showDeleteConfirmation = true
                    } label: {
                        Label("Delete Project", systemImage: "trash")
                    }
                } label: {
                    Image(systemName: "ellipsis.circle")
                }
                .accessibilityLabel("More options")
                .accessibilityHint("Edit or delete this project")
                .disabled(viewModel.project == nil || isDeleting)
            }
        }
        .confirmationDialog(
            "Delete Project",
            isPresented: $showDeleteConfirmation,
            titleVisibility: .visible
        ) {
            Button("Delete Permanently", role: .destructive) {
                Task { await performProjectDeletion() }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("This will permanently delete the project and all linked photos, AI previews, materials, estimates, and proposals. This cannot be undone.")
        }
        .refreshable {
            await viewModel.loadProject(id: projectId)
        }
        .task {
            if viewModel.project == nil {
                await viewModel.loadProject(id: projectId)
            }
            maybeAutoGenerate()
        }
        .sheet(isPresented: $showEditSheet) {
            if let project = viewModel.project {
                ProjectEditSheet(project: project) { updated in
                    viewModel.project = updated
                    Task { await viewModel.loadProject(id: projectId) }
                }
            }
        }
        .sheet(item: $exportedPDF) { pdf in
            ActivityViewRepresentable(activityItems: [pdf.url])
        }
        .fullScreenCover(isPresented: $showLawnMeasurement, onDismiss: {
            // Project may have a fresh lawn_area / lat-lng after the user
            // saves — refresh so the detail screen shows the new value.
            Task { await viewModel.loadProject(id: projectId) }
        }) {
            if let project = viewModel.project {
                NavigationStack {
                    LawnMeasurementView(
                        viewModel: LawnMeasurementViewModel(
                            projectId: project.id,
                            initialCenter: lawnInitialCenter(for: project)
                        )
                    )
                }
            }
        }
        .fullScreenCover(isPresented: $showRoofScouting, onDismiss: {
            Task { await viewModel.loadProject(id: projectId) }
        }) {
            if let project = viewModel.project {
                NavigationStack {
                    RoofScoutingView(
                        viewModel: RoofScoutingViewModel(
                            projectId: project.id,
                            initialAddress: nil,
                            initialCoordinate: lawnInitialCenter(for: project)
                        )
                    )
                }
            }
        }
        .alert(
            "Error",
            isPresented: Binding(
                get: { viewModel.project != nil && viewModel.errorMessage != nil },
                set: { if !$0 { viewModel.errorMessage = nil } }
            )
        ) {
            Button("OK") { viewModel.errorMessage = nil }
        } message: {
            if let message = viewModel.errorMessage {
                Text(message)
            }
        }
    }

    // MARK: - Content

    private func projectContent(_ project: Project) -> some View {
        ScrollView {
            LazyVStack(spacing: SpacingTokens.lg) {
                // Overview
                ProjectOverviewSection(
                    project: project,
                    clientName: viewModel.clientName,
                    onClientTapped: {
                        if let clientId = project.clientId {
                            router.navigate(to: .clientDetail(id: clientId))
                        }
                    }
                )
                .padding(.horizontal, SpacingTokens.md)

                // Property scouting tools — surfaced for project types
                // where measured area materially changes the bid. Tapping
                // either button opens a dedicated screen that PATCHes the
                // result back onto the project.
                propertyScoutingSection(for: project)

                // Images
                ProjectImagesSection(assets: viewModel.assets)

                // AI Preview
                AIPreviewSection(
                    generations: viewModel.generations,
                    isGenerating: viewModel.isGenerating,
                    currentGenerationStage: viewModel.currentGenerationStage,
                    onGenerate: { prompt in
                        handleGenerate(prompt: prompt)
                    },
                    defaultPrompt: viewModel.project?.description ?? "",
                    assets: viewModel.assets
                )

                // AI Estimate Ready card (shown when backend auto-created an estimate)
                if let latestEstimate = viewModel.latestEstimate, viewModel.hasAIEstimate {
                    AIEstimateReadyCard(
                        estimate: latestEstimate,
                        onReview: {
                            handleExportEstimate(estimateId: latestEstimate.id)
                        }
                    )
                }

                // Materials
                MaterialSuggestionsSection(
                    materials: viewModel.materials,
                    selectionState: viewModel.materialSelectionState,
                    selectedCount: viewModel.selectedMaterialCount,
                    selectedTotal: viewModel.selectedMaterialsTotal,
                    isDIY: viewModel.isDIY,
                    hasExistingEstimate: viewModel.hasAIEstimate,
                    onToggle: { id in viewModel.toggleMaterial(id: id) },
                    onToggleDIY: { viewModel.isDIY.toggle() },
                    onAddToEstimate: {
                        handleCreateEstimate()
                    }
                )

                // Estimates
                ProjectEstimatesSection(
                    estimates: viewModel.estimates,
                    exports: viewModel.estimateExports,
                    exportingEstimateId: exportingEstimateId,
                    isGeneratingAI: isGeneratingAIEstimate,
                    onGenerateAI: {
                        handleGenerateAIEstimate()
                    },
                    onCreateEstimate: {
                        handleCreateEstimate()
                    },
                    onExportEstimate: { estimateId in
                        handleExportEstimate(estimateId: estimateId)
                    },
                    onTapSavedExport: { export in
                        handleTapSavedExport(export)
                    }
                )

                // Activity
                ProjectActivitySection(entries: viewModel.activityLog)

                // Bottom spacer
                Spacer(minLength: SpacingTokens.huge)
            }
            .padding(.vertical, SpacingTokens.sm)
        }
        .overlay {
            if isCreatingEstimate || isGeneratingAIEstimate || exportProgressMessage != nil {
                Color.black.opacity(0.2)
                    .ignoresSafeArea()
                    .overlay {
                        ProgressView(progressOverlayLabel)
                            .padding()
                            .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 12))
                    }
            }
        }
    }

    // MARK: - Property Scouting

    /// Lawn measurement is exposed for landscape / lawn-care projects;
    /// roof scouting for roofing / siding / exterior projects (anything
    /// with overhead work). Other types skip the section entirely so the
    /// detail page doesn't grow buttons no contractor would tap.
    @ViewBuilder
    private func propertyScoutingSection(for project: Project) -> some View {
        let showLawn = project.projectType == .lawnCare
            || project.projectType == .landscaping
        let showRoof = project.projectType == .roofing
            || project.projectType == .exterior
            || project.projectType == .siding

        if showLawn || showRoof {
            VStack(alignment: .leading, spacing: SpacingTokens.sm) {
                Text("Property Scouting")
                    .font(TypographyTokens.headline)
                    .padding(.horizontal, SpacingTokens.md)

                HStack(spacing: SpacingTokens.sm) {
                    if showLawn {
                        scoutingButton(
                            title: project.lawnAreaSqFt != nil
                                ? "Re-Measure Lawn"
                                : "Measure Lawn",
                            subtitle: project.lawnAreaSqFt != nil
                                ? "\(Int(NSDecimalNumber(decimal: project.lawnAreaSqFt!).doubleValue)) sq ft"
                                : "Tap to outline on map",
                            icon: "leaf.fill",
                            tint: ColorTokens.accentGreen
                        ) {
                            handleOpenMaps { showLawnMeasurement = true }
                        }
                    }
                    if showRoof {
                        scoutingButton(
                            title: project.roofAreaSqFt != nil
                                ? "Re-Scout Roof"
                                : "Scout Roof",
                            subtitle: project.roofAreaSqFt != nil
                                ? String(format: "%.1f squares", NSDecimalNumber(decimal: project.roofAreaSqFt!).doubleValue / 100)
                                : "Solar API report",
                            icon: "house.fill",
                            tint: ColorTokens.primaryOrange
                        ) {
                            handleOpenMaps { showRoofScouting = true }
                        }
                    }
                }
                .padding(.horizontal, SpacingTokens.md)
            }
        }
    }

    private func decimalToDouble(_ d: Decimal) -> Double {
        NSDecimalNumber(decimal: d).doubleValue
    }

    /// Resolves the best initial map center for the lawn / roof sheets.
    /// Prefers the project's saved lat/lng, otherwise nil so the
    /// measurement view falls back to its own search-driven flow.
    private func lawnInitialCenter(for project: Project) -> CLLocationCoordinate2D? {
        guard
            let lat = project.propertyLatitude,
            let lng = project.propertyLongitude
        else { return nil }
        return CLLocationCoordinate2D(
            latitude: NSDecimalNumber(decimal: lat).doubleValue,
            longitude: NSDecimalNumber(decimal: lng).doubleValue
        )
    }

    private func scoutingButton(
        title: String,
        subtitle: String,
        icon: String,
        tint: Color,
        action: @escaping () -> Void
    ) -> some View {
        Button(action: action) {
            HStack(spacing: SpacingTokens.sm) {
                Image(systemName: icon)
                    .font(.title3)
                    .foregroundStyle(tint)
                    .frame(width: 36, height: 36)
                    .background(tint.opacity(0.12), in: RoundedRectangle(cornerRadius: RadiusTokens.small))
                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(TypographyTokens.subheadline)
                        .fontWeight(.semibold)
                        .foregroundStyle(ColorTokens.primaryText)
                    Text(subtitle)
                        .font(TypographyTokens.caption)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                Image(systemName: "chevron.right")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
            }
            .padding(SpacingTokens.sm)
            .frame(maxWidth: .infinity)
            .glassCard(cornerRadius: RadiusTokens.card)
        }
        .buttonStyle(.plain)
    }

    // MARK: - Feature-Gated Actions

    /// Gate the lawn / roof scouting fullscreen presentations. Both
    /// hit billable Google APIs so a free user must upgrade first.
    /// Subscribed users (and trialing users) are passed through to
    /// the original `present` closure unchanged.
    private func handleOpenMaps(present: () -> Void) {
        let result = featureGateCoordinator.guardUseMaps()
        switch result {
        case .allowed:
            present()
        case let .blocked(decision):
            paywallPresenter.present(decision)
        }
    }

    private func handleGenerate(prompt: String) {
        let result = featureGateCoordinator.guardGeneratePreview()
        switch result {
        case .allowed:
            Task { await viewModel.startGeneration(prompt: prompt) }
        case let .blocked(decision):
            paywallPresenter.present(decision)
        }
    }

    private func handleCreateEstimate() {
        isCreatingEstimate = true
        Task {
            _ = await viewModel.createEstimate()
            isCreatingEstimate = false
            // The new estimate appears in the Estimates section and the user
            // taps "Export PDF" to generate the branded copy. On nil, the VM
            // sets errorMessage which surfaces via the .alert above.
        }
    }

    /// If the project was opened with `autoGenerateOnOpen == true` — the
    /// creation-flow toggle is on — kick off a preview generation using the
    /// project description as the prompt. Runs only once per view lifetime
    /// and only when there are no existing generations and no run is in
    /// flight. Paywall is still respected via `featureGateCoordinator`.
    private func maybeAutoGenerate() {
        guard autoGenerateOnOpen,
              !hasAutoGenerated,
              let project = viewModel.project,
              viewModel.generations.isEmpty,
              !viewModel.isGenerating,
              let description = project.description,
              !description.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        hasAutoGenerated = true
        handleGenerate(prompt: description)
    }

    private var progressOverlayLabel: String {
        if let exportProgressMessage { return exportProgressMessage }
        if isGeneratingAIEstimate { return "Generating estimate with AI..." }
        return "Creating estimate..."
    }

    /// "Generate with AI" CTA on the estimates section. Runs through the
    /// dedicated `guardGenerateAIEstimate()` Pro-only paywall gate, then
    /// hands the project to the backend which uses Gemini with a
    /// specialized estimator prompt to produce a full professional estimate
    /// keyed off the project's selected materials and the company's branding
    /// + settings.
    private func handleGenerateAIEstimate() {
        let result = featureGateCoordinator.guardGenerateAIEstimate()
        switch result {
        case .allowed:
            isGeneratingAIEstimate = true
            Task {
                _ = await viewModel.generateAIEstimate()
                isGeneratingAIEstimate = false
            }
        case let .blocked(decision):
            paywallPresenter.present(decision)
        }
    }

    private func performProjectDeletion() async {
        isDeleting = true
        defer { isDeleting = false }
        let succeeded = await viewModel.deleteProject()
        if succeeded {
            // Return to the Projects tab list by popping the navigation stack.
            appState.selectedTab = .projects
            router.projectsPath = NavigationPath()
        }
    }

    // MARK: - Estimate Export

    /// Per-row "Export PDF" handler. Same paywall gate as the in-editor
    /// export so a free user can't sneak around the quote-export limit by
    /// triggering from here. On success: render branded PDF, persist a copy
    /// server-side, refresh the saved-exports list, and present the share
    /// sheet — the same end-state the editor produces.
    private func handleExportEstimate(estimateId: String) {
        let result = featureGateCoordinator.guardExportQuote()
        switch result {
        case .allowed:
            guard exportingEstimateId == nil else { return }
            exportingEstimateId = estimateId
            exportProgressMessage = "Preparing estimate..."
            Task {
                let url = await performBrandedExport(estimateId: estimateId)
                if let url {
                    await persistExportToProject(url: url, estimateId: estimateId)
                }
                await MainActor.run {
                    if let url {
                        exportedPDF = ExportedPDF(url: url)
                    } else {
                        viewModel.errorMessage = "Couldn't build the PDF. Make sure the estimate has at least one line item and try again."
                    }
                    exportingEstimateId = nil
                    exportProgressMessage = nil
                }
            }
        case let .blocked(decision):
            paywallPresenter.present(decision)
        }
    }

    /// Tap on a previously-saved export row. We re-download the PDF binary
    /// from the public file endpoint into a temp file (so the share sheet
    /// can write to disk targets), then trigger the share sheet.
    private func handleTapSavedExport(_ export: EstimateExport) {
        guard exportingEstimateId == nil else { return }
        exportingEstimateId = export.estimateId
        exportProgressMessage = "Loading saved PDF..."
        Task {
            let url = await downloadSavedExport(export)
            await MainActor.run {
                if let url {
                    exportedPDF = ExportedPDF(url: url)
                } else {
                    viewModel.errorMessage = "Couldn't load the saved PDF. Check your connection and try again."
                }
                exportingEstimateId = nil
                exportProgressMessage = nil
            }
        }
    }

    /// Streams the saved PDF from the backend's public file endpoint into a
    /// temp file we can hand to `UIActivityViewController`. Uses URLSession
    /// directly (not APIClient) because the file endpoint serves binary,
    /// not the JSON envelope APIClient expects.
    private func downloadSavedExport(_ export: EstimateExport) async -> URL? {
        do {
            let (data, _) = try await URLSession.shared.data(from: export.downloadURL)
            let tmpDir = FileManager.default.temporaryDirectory
            let dest = tmpDir.appendingPathComponent(export.fileName)
            try? FileManager.default.removeItem(at: dest)
            try data.write(to: dest, options: .atomic)
            return dest
        } catch {
            return nil
        }
    }

    /// Render the branded PDF for a specific estimate by ID. Loads the
    /// estimate + line items via the live service and hands them to
    /// `EstimatePDFRenderer`. Each ancillary fetch is independently optional
    /// so a missing logo or generation doesn't kill the export.
    private func performBrandedExport(estimateId: String) async -> URL? {
        await setExportProgress("Fetching estimate...")

        let estimateService = LiveEstimateService()
        guard let estimate = try? await estimateService.getEstimate(id: estimateId) else { return nil }
        let lineItems = (try? await estimateService.getLineItems(estimateId: estimateId)) ?? []
        let projectId = estimate.projectId
        let isDIY = viewModel.isDIY

        await setExportProgress("Fetching branding...")

        let settingsService = LiveSettingsService()
        let projectService = LiveProjectService()

        async let companyTask: Company? = try? await settingsService.loadCompanySettings()
        async let projectTask: Project? = try? await projectService.getProject(id: projectId)
        async let assetsTask: [Asset] = (try? await APIClient.shared.request(.listAssets(projectId: projectId))) ?? []
        async let generationsTask: [AIGeneration] = (try? await APIClient.shared.request(.listGenerations(projectId: projectId))) ?? []

        let company = await companyTask
        let project = await projectTask
        let assets = await assetsTask
        let generations = await generationsTask

        await setExportProgress("Downloading images...")

        let beforeURL = assets
            .filter { $0.assetType == .original }
            .sorted { $0.sortOrder < $1.sortOrder || ($0.sortOrder == $1.sortOrder && $0.createdAt < $1.createdAt) }
            .first?
            .url

        let afterURL = generations
            .filter { $0.status == .completed }
            .sorted { $0.createdAt > $1.createdAt }
            .first?
            .previewURL

        let logoURL = company?.logoURL ?? appState.currentCompany?.logoURL

        async let logoFetch: UIImage? = logoURL.flatMap { url in Task { try? await ImageFetcher.fetch(url) } }?.value
        async let beforeFetch: UIImage? = (includeBeforeAfterImages ? beforeURL : nil)
            .flatMap { url in Task { try? await ImageFetcher.fetch(url) } }?.value
        async let afterFetch: UIImage? = (includeBeforeAfterImages ? afterURL : nil)
            .flatMap { url in Task { try? await ImageFetcher.fetch(url) } }?.value

        let logoImage = await logoFetch
        let beforeImage = await beforeFetch
        let afterImage = await afterFetch

        let clientInfo = await resolveClient(for: project)
        let branding = buildBranding(from: company, logoImage: logoImage)

        await setExportProgress("Rendering PDF...")

        return await MainActor.run {
            EstimatePDFRenderer.render(
                estimate: estimate,
                lineItems: lineItems,
                isDIY: isDIY,
                branding: branding,
                client: clientInfo,
                beforeImage: beforeImage,
                afterImage: afterImage,
                projectTitle: project?.title
            )
        }
    }

    /// Upload the freshly-rendered PDF so it appears under the estimate row
    /// next time the project loads. Fail-soft: any upload error is
    /// swallowed so the user still gets their local file via the share
    /// sheet. On success we register the new export locally so the row's
    /// "Saved" sublist updates immediately without a full project reload.
    private func persistExportToProject(url: URL, estimateId: String) async {
        await setExportProgress("Saving to project...")
        do {
            let data = try Data(contentsOf: url)
            let fileName = url.lastPathComponent
            let service = LiveEstimateExportService()
            let saved = try await service.upload(
                estimateId: estimateId,
                fileName: fileName,
                pdfData: data
            )
            await MainActor.run {
                viewModel.registerNewExport(saved)
            }
        } catch {
            // Non-fatal: contractor still has the local copy.
        }
    }

    @MainActor
    private func setExportProgress(_ message: String) {
        exportProgressMessage = message
    }

    /// Look up the project's client and shape it into the PDF's
    /// "Prepared For" block. Returns nil if the project has no client or
    /// if the lookup fails — the PDF renders fine without it.
    private func resolveClient(for project: Project?) async -> PDFGenerator.ClientInfo? {
        guard let clientId = project?.clientId, !clientId.isEmpty else { return nil }
        guard let record: Client = try? await APIClient.shared.request(.getClient(id: clientId)) else {
            return nil
        }
        let addressLines = AppState.CurrentCompany.composeAddressLines(
            street: record.address,
            city: record.city,
            state: record.state,
            zip: record.zip
        )
        return PDFGenerator.ClientInfo(
            name: record.name,
            company: nil,
            phone: record.phone,
            email: record.email,
            addressLines: addressLines
        )
    }

    /// Compose the branding block from the freshest available source —
    /// the network-fetched Company first, then the AppState snapshot, then
    /// bare defaults — so an offline export still produces a recognizable
    /// header.
    private func buildBranding(from company: Company?, logoImage: UIImage?) -> PDFGenerator.CompanyBranding {
        if let company {
            let addressLines = AppState.CurrentCompany.composeAddressLines(
                street: company.address,
                city: company.city,
                state: company.state,
                zip: company.zip
            )
            return PDFGenerator.CompanyBranding(
                name: company.name,
                phone: company.phone,
                email: company.email,
                addressLines: addressLines,
                websiteUrl: company.websiteUrl,
                logoImage: logoImage,
                accentHex: company.primaryColor
            )
        }
        let snapshot = appState.currentCompany
        return PDFGenerator.CompanyBranding(
            name: snapshot?.name ?? "ProEstimate AI",
            phone: snapshot?.phone,
            email: snapshot?.email,
            addressLines: snapshot?.addressLines ?? [],
            websiteUrl: snapshot?.websiteUrl,
            logoImage: logoImage,
            accentHex: snapshot?.primaryColorHex
        )
    }
}

// MARK: - Preview

#Preview {
    NavigationStack {
        ProjectDetailView(projectId: "p-001")
    }
    .environment(AppRouter())
    .environment(FeatureGateCoordinator.preview())
    .environment(PaywallPresenter())
}
